### ISSUE TITLE
flask init时候出现问题，无法解决，求助大佬

### ISSUE THREAD

**Issue by GXL911** [weijiang1994/university-bbs#21]
在一开始，我flask init的时候，会出现yaml文件的报错
 File "/home/gu/must/.env/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/home/gu/must/university-bbs/conf/config.yml", line 2, column 3
expected <block end>, but found '<block mapping start>'
  in "/home/gu/must/university-bbs/conf/config.yml", line 10, column 5
可能是格式有问题，然后我更改了一下格式，变成图片的样子，然后原来的报错消失了，出现了一个新的错误
Traceback (most recent call last):
  File "/home/gu/must/.env/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/gu/must/.env/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/gu/must/.env/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/gu/must/.env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/gu/must/.env/lib/python3.8/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/gu/must/.env/lib/python3.8/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/gu/must/.env/lib/python3.8/site-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/home/gu/must/.env/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/home/gu/must/.env/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/gu/must/university-bbs/bbs/__init__.py", line 17, in <module>
    from bbs.blueprint.auth import auth_bp
  File "/home/gu/must/university-bbs/bbs/blueprint/auth.py", line 17, in <module>
    from bbs.utils import Config, generate_token, validate_token, generate_ver_code, deserialize_token, ip_recognized, \
  File "/home/gu/must/university-bbs/bbs/utils.py", line 188, in <module>
    ip_recognized = IPRecognize(path=os.path.join(basedir, 'conf/config.yml'))
  File "/home/gu/must/university-bbs/bbs/utils.py", line 172, in __init__
    self.token, self.url = self.init_ipinfo(path)
  File "/home/gu/must/university-bbs/bbs/utils.py", line 181, in init_ipinfo
    return values.get('token'), values.get('url')
AttributeError: 'str' object has no attribute 'get'
希望大佬能够帮帮我，十分感谢你在知乎上面的教程
![微信图片_20230416130610](https://user-images.githubusercontent.com/53310167/232272072-61dea433-fbfe-4e5f-898f-02c1eb303576.jpg)

**Comment by weijiang1994** [comment]
@GXL911 yaml文件格式错了,`ip-recognize` key应该`oauth`是同级的，改成下面这种
```yaml
admin:
  audit: true # enable or disable user post need to audit.
  register: true # enable or disable register
  upload-img: 1024 # the max size of image that user can upload.
  mail: # website admin mail account to receive website notify.
  backend_url: http://127.0.0.1:8008 # manage url
  category_img: # post category image save path.
  oauth: true # enable or disable third party login like github google etc.
  ip-recognize: # recognized user login and comment ip address belong where.
    token: xxx # type your token of apispace
    url: https://eolink.o.apispace.com/ipguishu/ip/geo/v1/district
  third-party:
    github:
      enable: true
      name: Github
      icon: /static/img/github.svg
    gitee:
      enable: true
      name: Gitee
      icon: /static/img/gitee.svg
    oschina:
      enable: false
      name: OSChina
      icon: /static/img/oschina.svg
    stackoverflow:
      enable: false
      name: StackOverflow
      icon: /static/img/stackoverflow.svg
website:
  domain: http://127.0.0.1:5000 # website domain
  name: University-BBS # website name
```
